language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

services:
  - mongodb

install:
  - pip install -r requirements.txt

before_script:
  - sleep 15
  - mongo gitcrawl --eval 'db.addUser("YOUR_USERNAME", "YOUR_PASSWORD");'

script:
  - python Launcher.py
  - python Exporter.py
