language: python

services:
  - mongodb

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

install:
  - "pip install -r requirements.txt"

before_script:
  - sleep 15
  - mongo gitcrawl --eval 'db.addUser("YOUR_USERNAME", "YOUR_PASSWORD");'

script:
  - python Launcher.py
